# roles/rdir/tasks/absent.yml
---
- name: absent - Reset defaults
  set_fact:
    openio_rdir_servicename: "{{ rd.ansible_facts._rdir.name }}"
    openio_rdir_bind_port: "{{ rd.ansible_facts._rdir.port }}"
    openio_rdir_serviceid: "{{ rd.ansible_facts._rdir.id }}"
    openio_rdir_volume: "{{ rd.ansible_facts._rdir.volume }}"


- name: absent - Remove configuration files
  file:
    dest: "{{ item.dest }}"
    state: absent
  with_items:
    - dest: "{{ openio_rdir_sysconfig_dir }}/\
        {{ openio_rdir_servicename }}/{{ openio_rdir_servicename }}-httpd.conf"
    - dest: "{{ openio_rdir_gridinit_dir }}/{{ openio_rdir_gridinit_file_prefix }}\
        {{ openio_rdir_servicename }}.conf"
    - dest: "{{ openio_rdir_sysconfig_dir }}/watch/{{ openio_rdir_servicename }}.yml"
  register: _rdir_conf

- block:
    - name: absent - stop rdir to apply the new configuration
      shell: gridinit_cmd stop  {{ openio_rdir_namespace }}-{{ openio_rdir_servicename }}

    - name: absent - Set properties
      set_fact:
        need_reload: true
  when:
    - _rdir_conf is changed
    - not openio_rdir_provision_only

...
