# roles/rdir/tasks/absent.yml
---
- name: absent - Reset defaults
  set_fact:
    _openio_rdir_servicename: "{{ rd.ansible_facts._rdir.name }}"
    _openio_rdir_bind_port: "{{ rd.ansible_facts._rdir.port }}"
    _openio_rdir_serviceid: "{{ rd.ansible_facts._rdir.id }}"
    _openio_rdir_volume: "{{ rd.ansible_facts._rdir.volume }}"
  tags:
    - install
    - configure

- name: absent - Remove configuration files
  file:
    dest: "{{ item.dest }}"
    state: absent
  with_items:
    - dest: "{{ openio_rdir_sysconfig_dir }}/\
        {{ _openio_rdir_servicename }}/{{ _openio_rdir_servicename }}-httpd.conf"
    - dest: "{{ openio_rdir_gridinit_dir }}/{{ openio_rdir_gridinit_file_prefix }}\
        {{ _openio_rdir_servicename }}.conf"
    - dest: "{{ openio_rdir_sysconfig_dir }}/watch/{{ _openio_rdir_servicename }}.yml"
  register: _rdir_conf
  tags: configure

- block:
    - name: absent - stop rdir to apply the new configuration
      shell: gridinit_cmd stop  {{ openio_rdir_namespace }}-{{ _openio_rdir_servicename }}

    - name: absent - Set properties
      set_fact:
        need_reload: true
  when:
    - _rdir_conf is changed
    - not openio_rdir_provision_only
  tags: configure
...
