# roles/rdir/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_rdir_namespace }}"
    - path: "{{ openio_rdir_sysconfig_dir }}/{{ openio_rdir_servicename }}"
    - path: "{{ openio_rdir_volume }}"
    - path: "/etc/oio/sds/{{ openio_rdir_namespace }}/watch"
    - path: "/var/log/oio/sds/{{ openio_rdir_namespace }}/{{ openio_rdir_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "rdir.conf.j2"
      dest: "{{ openio_rdir_sysconfig_dir }}/\
        {{ openio_rdir_servicename }}/{{ openio_rdir_servicename }}.conf"
    - src: "gridinit_rdir.conf.j2"
      dest: "{{ openio_rdir_gridinit_dir }}/{{ openio_rdir_gridinit_file_prefix }}\
        {{ openio_rdir_servicename }}.conf"
    - src: "watch-rdir.yml.j2"
      dest: "{{ openio_rdir_sysconfig_dir }}/watch/{{ openio_rdir_servicename }}.yml"
  register: _rdir_conf

- name: restart rdir
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_rdir_namespace }}-{{ openio_rdir_servicename }}
  when:
    - _rdir_conf.changed
    - not openio_rdir_provision_only
  tags: configure
...
