# roles/rdir/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_rdir_namespace }}"
    - "{{ openio_rdir_sysconfig_dir }}/rdir-{{ openio_rdir_serviceid }}"
    - "{{ openio_rdir_volume }}"
    - "/etc/oio/sds/{{ openio_rdir_namespace }}/watch"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0750
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Ensure log directory
  file:
    path: "/var/log/oio/sds/{{ openio_rdir_namespace }}/rdir-{{ openio_rdir_serviceid }}"
    state: directory
    owner: "{{ syslog_user }}"
    group: openio
    mode: 0750
    recurse: true
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "rdir.conf.j2"
      dest: "{{ openio_rdir_sysconfig_dir }}/\
        rdir-{{ openio_rdir_serviceid }}/rdir-{{ openio_rdir_serviceid }}.conf"
    - src: "gridinit_rdir.conf.j2"
      dest: "{{ openio_rdir_gridinit_dir }}/{{ openio_rdir_gridinit_file_prefix }}\
        rdir-{{ openio_rdir_serviceid }}.conf"
    - src: "watch-rdir.yml.j2"
      dest: "{{ openio_rdir_sysconfig_dir }}/watch/rdir-{{ openio_rdir_serviceid }}.yml"
  register: _rdir_conf

- name: restart rdir
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_rdir_namespace}}-rdir-{{openio_rdir_serviceid}}
  when:
    - _rdir_conf.changed
    - not openio_rdir_provision_only
  tags: configure
...
