# roles/rdir/tasks/offline.yml
---
- name: offline - Reset defaults
  set_fact:
    _openio_rdir_servicename: "{{ rd.ansible_facts._rdir.name }}"
    _openio_rdir_bind_port: "{{ rd.ansible_facts._rdir.port }}"
    _openio_rdir_serviceid: "{{ rd.ansible_facts._rdir.id }}"
    _openio_rdir_volume: "{{ rd.ansible_facts._rdir.volume }}"
    _openio_rdir_state: "{{ rd.ansible_facts._rdir.state }}"
  tags:
    - install
    - configure

- name: offline - Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0640
  with_items:
    - src: "gridinit_rdir.conf.j2"
      dest: "{{ openio_rdir_gridinit_dir }}/{{ openio_rdir_gridinit_file_prefix }}\
        {{ _openio_rdir_servicename }}.conf"
  register: _rdir_conf
  tags: configure

- block:
    - name: offline - stop rdir to apply the new configuration
      shell: gridinit_cmd stop  {{ openio_rdir_namespace }}-{{ _openio_rdir_servicename }}

    - name: offline - Set properties
      set_fact:
        need_reload: true
  when:
    - _rdir_conf is changed
    - not openio_rdir_provision_only
  tags: configure
...
