# Test playbook
---
- hosts: all
  become: true
  vars:
    NS: TRAVIS
    openio_bootstrap: true
  roles:
    - role: users
    - role: repository
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_per_ns: true
    - role: namespace
      openio_namespace_name: "{{ NS }}"
    - role: role_under_test
      openio_rdir_namespace: "{{ NS }}"
      openio_rdir_instances:
        - id: "5"
          port: 6301
          state: "present"
          volume: "/var/lib/oio/sds/{{ openio_rdir_namespace }}/am"
        - id: "2"
          port: 6302
          state: "absent"
          volume: "/var/lib/oio/sds/{{ openio_rdir_namespace }}/stram"
        - id: "3"
          port: 6303
          state: "offline"
          volume: "/var/lib/oio/sds/{{ openio_rdir_namespace }}/gram"
...
